### ISSUE TITLE
flutter repo pub.dev, outdated version

### ISSUE THREAD

**Issue by aap17** [MadBrains/Yandex-Geocoder-Flutter#13]
Could you please update library version that published in pub.dev? Now it's only `2.1.0` with outdated dependency

```
Because yandex_geocoder >=2.1.0 depends on http ^0.13.5 and app_flutter depends on http ^1.1.0, yandex_geocoder >=2.1.0 is forbidden.
So, because app_flutter depends on yandex_geocoder ^2.1.0, version solving failed.

```

It's ok with your last version `2.2.0`, it would be great to see it in pub.dev.

**Comment by mit-73** [comment]
Updated in https://github.com/MadBrains/Yandex-Geocoder-Flutter/pull/14
